name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Build production app
        run: ./scripts/buildprod.sh

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-471203
          version: 'latest'

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Verify authentication
        run: |
          gcloud auth list
          gcloud config get-value account
          gcloud config get-value project

      - name: Build and Push Docker image
        run: |
          gcloud builds submit \
            --project notely-471203 \
            --tag us-central1-docker.pkg.dev/notely-471203/notely-ar-repo/notely:latest .
