name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      # 3. Build the production application
      - name: Build production app
        run: ./scripts/buildprod.sh

      # 4. Set up gcloud CLI and authenticate with service account
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      # 5. Explicitly set the GCP project (optional but recommended)
      - name: Set GCP project
        run: gcloud config set project notely-471203

      # 6. Build and push Docker image using Cloud Build
      - name: Build and Push Docker image
        run: |
          gcloud builds submit \
            --project notely-471203 \
            --tag us-central1-docker.pkg.dev/notely-471203/notely-ar-repo/notely:latest .
