name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      # 3. Build production app
      - name: Build production app
        run: ./scripts/buildprod.sh

      # 4. Minimal gcloud auth setup
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      # 5. Verify authentication
      - name: Verify gcloud authentication
        run: |
          gcloud auth list
          gcloud config list

      # 6. Build and push Docker image
      - name: Build and Push Docker image
        run: |
          gcloud builds submit \
            --project notely-471203 \
            --tag us-central1-docker.pkg.dev/notely-471203/notely-ar-repo/notely:latest .
