name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      # 3. Build the production app
      - name: Build production app
        run: ./scripts/buildprod.sh

      # 4. Authenticate to GCP first
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # 5. Install gcloud CLI and set project
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-471203
          version: 'latest'

      # 6. Verify authentication
      - name: Verify gcloud authentication
        run: |
          gcloud auth list
          gcloud config get-value account
          gcloud config get-value project

      # 7. Build and push Docker image via Cloud Build
      - name: Build and Push Docker image
        run: |
          gcloud builds submit \
            --project notely-471203 \
            --tag us-central1-docker.pkg.dev/notely-471203/notely-ar-repo/notely:latest .
      # 8. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-471203/notely-ar-repo/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-471203 \
            --max-instances=4